<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net45</TargetFramework>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <RestorePackagesPath>..\..\vendor\</RestorePackagesPath>
    <RootNamespace>Lidgren.Network.MonoGame</RootNamespace>
    <AssemblyName>Lidgren.Network.MonoGame</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <OutputPath>..\..\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Lidgren.Network, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Lidgren.Network.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.7.1.189" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
