<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TargetFrameworkVersion>v8.0</TargetFrameworkVersion>
    <GenerateDependencyFile>False</GenerateDependencyFile>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
    <RestorePackagesPath>..\..\vendor\</RestorePackagesPath>
    <RootNamespace>Lidgren.Network.MonoGame</RootNamespace>
    <AssemblyName>Lidgren.Network.MonoGame</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <OutputPath>..\..\bin\</OutputPath>
    <PublishDir>..\..\bin\</PublishDir>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Lidgren.Network, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Lidgren.Network.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>
</Project>
